//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace super_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class seller
    {
        public string Sell_ID { get; set; }
        public string Sell_Name { get; set; }
        public string Sell_Age { get; set; }
        public string Sell_no { get; set; }
        public string Passwords { get; set; }
    }
}
